pipeline {
    agent any
    environment {
        DOCKERHUB_USERNAME = 'vikash8058'
        IMAGE_NAME = 'bookstore-backend'
        EC2_IP = '54.226.175.107'
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from GitHub...'
                checkout scm
            }
        }
        stage('Build JAR') {
            steps {
                echo 'Building JAR...'
                dir('OnlineBookStore') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t vikash8058/$IMAGE_NAME:latest ./OnlineBookStore/'
            }
        }
        stage('Push to DockerHub') {
            steps {
                echo 'Pushing to DockerHub...'
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push vikash8058/$IMAGE_NAME:latest'
                }
            }
        }
        stage('Deploy to EC2') {
    		steps {
       			 sh '''
        		 ssh -i /var/jenkins_home/bookstore-key.pem \
        		 -o StrictHostKeyChecking=no ubuntu@54.226.175.107 \
        		 "cd ~/bookstore && \
        	 	 docker pull vikash8058/bookstore-backend:latest && \
        		 docker compose up -d backend || docker-compose up -d backend"
       			 '''
    		}
	}
    }
    post {
        success { echo '✅ Backend deployed successfully!' }
        failure { echo '❌ Pipeline failed!' }
    }
}
